from app.models.auth_session import AuthSession
from app.models.diet_coach import (
    Canteen,
    CanteenDish,
    CanteenStall,
    CoachConversation,
    CoachMessage,
    DietAdjustment,
    HungerLog,
    PersonalDietaryMemory,
    PersonalEnergyModel,
    SavedMeal,
    SavedMealItem,
)
from app.models.food import FoodAlias, FoodFavorite, FoodItem
from app.models.health_activity import (
    ActivityLog,
    HealthPermissionState,
    HealthSyncState,
    RecoverySnapshot,
    SleepLog,
    StepLog,
)
from app.models.health_knowledge import (
    HealthAIConversation,
    HealthAIMessage,
    HealthCheckSuggestion,
    KnowledgeChunk,
    KnowledgeDocument,
    KnowledgeIngestionJob,
    LabOCRItem,
    LabOCRSession,
    LabReport,
    LabReportPage,
    LabResult,
    LabTestDictionary,
)
from app.models.health_profile import HealthProfile
from app.models.meal import MealItem, MealLog
from app.models.meal_analysis import (
    AIUsageLog,
    MealAnalysisItem,
    MealAnalysisSession,
    MealImage,
    PersonalFoodMemory,
)
from app.models.nutrition_goal import NutritionGoal
from app.models.training import (
    Exercise,
    ExercisePR,
    PainLog,
    TrainingAdjustment,
    TrainingDay,
    TrainingExercise,
    TrainingPlan,
    WorkoutSession,
    WorkoutSet,
)
from app.models.user import User
from app.models.weight_log import WeightLog

__all__ = [
    "AuthSession",
    "FoodAlias",
    "FoodFavorite",
    "FoodItem",
    "HealthProfile",
    "HealthAIConversation",
    "HealthAIMessage",
    "HealthCheckSuggestion",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "KnowledgeIngestionJob",
    "LabOCRItem",
    "LabOCRSession",
    "LabReport",
    "LabReportPage",
    "LabResult",
    "LabTestDictionary",
    "ActivityLog",
    "HealthPermissionState",
    "HealthSyncState",
    "RecoverySnapshot",
    "SleepLog",
    "StepLog",
    "Canteen",
    "CanteenDish",
    "CanteenStall",
    "CoachConversation",
    "CoachMessage",
    "DietAdjustment",
    "HungerLog",
    "PersonalDietaryMemory",
    "PersonalEnergyModel",
    "SavedMeal",
    "SavedMealItem",
    "MealItem",
    "MealLog",
    "AIUsageLog",
    "MealAnalysisItem",
    "MealAnalysisSession",
    "MealImage",
    "NutritionGoal",
    "Exercise",
    "ExercisePR",
    "PainLog",
    "TrainingAdjustment",
    "TrainingDay",
    "TrainingExercise",
    "TrainingPlan",
    "WorkoutSession",
    "WorkoutSet",
    "PersonalFoodMemory",
    "User",
    "WeightLog",
]
