from typing import Protocol


class StorageProvider(Protocol):
    async def put_private(
        self, data: bytes, content_type: str, suffix: str, prefix: str = ""
    ) -> str: ...

    async def read_bytes(self, object_key: str) -> bytes: ...

    async def delete(self, object_key: str) -> None: ...

    async def signed_read_url(self, object_key: str, expires_seconds: int = 300) -> str: ...
